" enable syntax highlighting
syntax enable

" attempt to determine the file type based on name and content
filetype plugin indent on

" set solarized dark as the color scheme
set background=dark
colorscheme solarized

" allow switching between buffers without saving first
set hidden

" use 4 spaces instead of tabs
set shiftwidth=4
set softtabstop=4
set expandtab

" if no known file type keep the same indent as the current line
set autoindent

" backspace through anything in insert mode
set backspace=indent,eol,start

" highlight search results and start searching immediately
set hlsearch
set incsearch

" always show at least one line above/below the cursor (and 5 on each side if
" not wrapping
set scrolloff=1
set sidescrolloff=5

" display the cursor position in the status line
set ruler

" display the line number on the left
set number

" display a column at 120 char
set colorcolumn=120

" highlight the current line
set cursorline

" always show the status line even when there is only one window
set laststatus=2

" autoload file changes
set autoread

" map screen redraw to also turn off search highlighting
nnoremap <C-L> :nohl<CR><C-L>

" vim-plug plugins
call plug#begin('~/.vim-plug-plugins')
Plug 'dag/vim-fish'
Plug 'rhysd/vim-clang-format'
Plug 'mileszs/ack.vim'
call plug#end()

" use `ag` in the `ack` plugin if it's available
if executable('ag')
    let g:ackprg = 'ag --vimgrep'
endif
