tap "1password/tap"
tap "github/gh"

cask_args appdir: "/Applications", require_sha: true, no_quarantine: true

# ============== Shell ==============

brew "bash"
brew "bat"
brew "curl"
brew "dasel"
brew "difftastic"
brew "dust"
brew "eza"
brew "fd"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "htop"
brew "hyperfine"
brew "koenbollen/public/jl"
brew "jless"
brew "jq"
brew "lazygit"
brew "neofetch"
brew "neovim"
brew "openssh"
brew "readline"
brew "ripgrep"
brew "stow"
brew "teamookla/speedtest/speedtest"
brew "tmux"
brew "vim"
brew "wget"
brew "zoxide"

# =========== Development ===========

brew "buildifier"
brew "buf"
brew "checkbashisms"
brew "clang-format"
brew "cmake"
brew "colima"
brew "docker"
brew "docker-buildx", postinstall: "mkdir -p $HOME/.docker/cli-plugins && ln -sfn /opt/homebrew/opt/docker-buildx/bin/docker-buildx $HOME/.docker/cli-plugins/docker-buildx"
brew "docker-compose", postinstall: "mkdir -p $HOME/.docker/cli-plugins && ln -sfn /opt/homebrew/opt/docker-buildx/bin/docker-compose $HOME/.docker/cli-plugins/docker-compose"
brew "golang"
brew "isort"
brew "luarocks"
brew "ninja"
brew "node"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ruff"
brew "shellcheck"
brew "shfmt"
brew "stylua"
brew "terraform"

# =============== LSP ===============

brew "bash-language-server"
brew "gopls"
brew "lua-language-server"
brew "pyright"
brew "rust-analyzer"
brew "terraform-ls"
brew "typescript-language-server"
brew "yaml-language-server"

# ============== Fonts ==============

cask "font-anonymous-pro"
cask "font-anonymice-nerd-font"

# ============== Apps ===============

cask "1password/tap/1password-cli"
cask "1password"
cask "alacritty", postinstall: "$HOME/scripts/bin/macos/.local/bin/codesign-alacritty"
cask "alfred@4"
cask "dropbox"
cask "google-chrome", args: { require_sha: false }
cask "istat-menus", args: { require_sha: false }
cask "mos"
cask "soundsource", args: { require_sha: false }
cask "spotify", args: { require_sha: false }
cask "stay"
