font-size = 14
adjust-cell-height = 5

window-width = 100
window-height = 40
macos-titlebar-style = native

macos-option-as-alt = true
keybind = super+shift+c=copy_to_clipboard
keybind = super+shift+v=paste_from_clipboard
keybind = super+n=new_window
