live_config_reload: true

env:
  TERM: xterm-256color

working_directory: ~

scrolling:
  history: 100000

window:
  startup_mode: Windowed
  decorations: full
  dimensions:
    columns: 100
    lines: 40
  title: Alacritty
  dynamic_title: false
  padding:
    x: 4
    y: 2
  gtk_theme_variant: dark

font:
  normal:
    family: Anonymous Pro
    style: Regular
  bold:
    family: Anonymous Pro
    style: Regular
  size: 12
  offset:
    y: 3
  use_thin_strokes: true

cursor:
  style: Block
  unfocused_hollow: true

colors:
  cursor:
    text: CellBackground
    cursor: "#d5ba9b"

draw_bold_text_with_bright_colors: false

bell:
  duration: 0
  command: None

# Doesn't seem to have any effect on macOS (where I need it)
# alt_send_esc: true

key_bindings:
  # On macOS Option doesn't act as a meta alt key (send the esc sequence) and unfortunately Alacritty doesn't support
  # remapping the modifier entirely (and `alt_send_esc` doesn't seem to work, at least in the shell)
  # So instead we remap the bindings that we care about.
  - { key: S,        mods: Alt, chars: "\x1bs",                      }
  - { key: C,        mods: Alt, chars: "\x1bc",                      }
