live_config_reload: true
working_directory: ~

env:
  TERM: alacritty

scrolling:
  history: 100000

cursor:
  style: Block
  blinking: Off
  unfocused_hollow: true

# Base16 Gruvbox dark, pale 256
# https://github.com/aarowill/base16-alacritty/blob/master/colors/base16-gruvbox-dark-pale-256.yml
colors:
  primary:
    background: '0x262626'
    foreground: '0xdab997'
  cursor:
    text: '0x262626'
    cursor: '0xdab997'
  normal:
    black:   '0x262626'
    red:     '0xd75f5f'
    green:   '0xafaf00'
    yellow:  '0xffaf00'
    blue:    '0x83adad'
    magenta: '0xd485ad'
    cyan:    '0x85ad85'
    white:   '0xdab997'
  bright:
    black:   '0x8a8a8a'
    red:     '0xd75f5f'
    green:   '0xafaf00'
    yellow:  '0xffaf00'
    blue:    '0x83adad'
    magenta: '0xd485ad'
    cyan:    '0x85ad85'
    white:   '0xebdbb2'
  indexed_colors:
    - { index: 16, color: '0xff8700' }
    - { index: 17, color: '0xd65d0e' }
    - { index: 18, color: '0x3a3a3a' }
    - { index: 19, color: '0x4e4e4e' }
    - { index: 20, color: '0x949494' }
    - { index: 21, color: '0xd5c4a1' }

draw_bold_text_with_bright_colors: true

bell:
  duration: 0
  command: None

window:
  startup_mode: Windowed
  decorations: full
  title: Alacritty
  dynamic_title: false

font:
  normal:
    family: Anonymous Pro
    style: Regular
  bold:
    family: Anonymous Pro
    style: Regular
  italic:
    family: Anonymous Pro
    style: Italic
  bold_italic:
    family: Anonymous Pro
    style: Italic
