#!/bin/bash

# If we're over an active SSH connection we should just use the forwarded agent.
if [ -n "$TMUX" ]; then
  if [[ $(tmux show-environment SSH_CONNECTION) == *=* ]]; then
    exit 1
  fi
else
  if [ -n "$SSH_CONNECTION" ]; then
    exit 1
  fi
fi

# Only use Secretive if the socket exists (either as a socket or a symlink to one).
[ -e "$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh" ] && exit 0 || exit 1
