local xdg = require("damien.xdg")

local Plug = vim.fn['plug#']

vim.call("plug#begin", xdg.config_dir .. "/nvim/plugged")

  Plug('chriskempson/base16-vim')
  Plug('dag/vim-fish')
  Plug('fatih/vim-go')
  Plug('itchyny/lightline.vim')
  Plug('junegunn/fzf', { ['dir'] = xdg.data_dir .. '/fzf', ['do'] = vim.fn["fzf#install"] })
  Plug('junegunn/fzf.vim')
  Plug('mhinz/vim-grepper')
  Plug('mhinz/vim-startify')
  Plug('rust-lang/rust.vim')
  Plug('tpope/vim-commentary')
  Plug('tpope/vim-eunuch')
  Plug('tpope/vim-fugitive')
  Plug('tpope/vim-git')
  Plug('tpope/vim-repeat')
  Plug('tpope/vim-rhubarb')
  Plug('tpope/vim-sleuth')
  Plug('tpope/vim-surround')
  Plug('tpope/vim-unimpaired')
  Plug('tpope/vim-vinegar')
  Plug('vimwiki/vimwiki')
  Plug('machakann/vim-highlightedyank')
  Plug('google/vim-maktaba')
  Plug('google/vim-codefmt')
  Plug('baskerville/vim-sxhkdrc')
  Plug('hashivim/vim-terraform')
  Plug('neovim/nvim-lspconfig')
  Plug('hrsh7th/nvim-cmp')
  Plug('hrsh7th/cmp-nvim-lsp')
  Plug('hrsh7th/cmp-buffer')
  Plug('hrsh7th/cmp-path')
  Plug('hrsh7th/cmp-nvim-lua')
  Plug('hrsh7th/vim-vsnip')
  Plug('hrsh7th/cmp-vsnip')
  Plug('kosayoda/nvim-lightbulb')
  Plug('nvim-lua/lsp-status.nvim')
  Plug('nvim-telescope/telescope.nvim')
  Plug('nvim-lua/popup.nvim')
  Plug('nvim-lua/plenary.nvim')
  Plug('nvim-treesitter/nvim-treesitter', { ['do'] = vim.fn[':TSUpdate'] })

vim.call("plug#end")
