" enable syntax highlighting
syntax enable

" attempt to determine the file type based on name and content
filetype plugin indent on

" vim-plug plugins
call plug#begin('~/.vim-plug-plugins')
    Plug 'dag/vim-fish'
    Plug 'mileszs/ack.vim'
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
    Plug 'junegunn/fzf.vim'
    Plug 'itchyny/lightline.vim'
    Plug 'tpope/vim-fugitive'
    Plug 'vim-scripts/a.vim'
    Plug 'rust-lang/rust.vim'
    Plug 'rhysd/vim-clang-format'
call plug#end()

" set solarized dark as the color scheme
set background=dark
colorscheme solarized

" allow switching between buffers without saving first
set hidden

" use 4 spaces instead of tabs
set shiftwidth=4
set softtabstop=4
set expandtab

" if no known file type keep the same indent as the current line
set autoindent

" backspace through anything in insert mode
set backspace=indent,eol,start

" highlight search results and start searching immediately
set hlsearch
set incsearch

" always show at least one line above/below the cursor (and 5 on each side if
" not wrapping
set scrolloff=1
set sidescrolloff=5

" display the cursor position in the status line
set ruler

" display the line number on the left
set number

" display a column at 120 char
set colorcolumn=120

" highlight the current line
set cursorline

" always show the status line even when there is only one window
set laststatus=2

" autoload file changes
set autoread

" map screen redraw to also turn off search highlighting
nnoremap <C-L> :nohl<CR><C-L>

" remap some `fzf` functions
nmap ; :Buffers<CR>
nmap <Leader>t :Files<CR>
nmap <Leader>r :Tags<CR>
nmap <Leader>a :Ag<CR>

" use `ag` in the `ack` plugin if it's available
if executable('ag')
    " use `ag` over grep
    set grepprg=ag\ --nogroup\ --nocolor
    let g:ackprg='ag --nogroup --nocolor --column'
endif
