[window]
# Windows don't need decoration in bspwm
decorations = "none"
decorations_theme_variant = "Dark"
dynamic_padding = true

# Let the window manager set the appropriate dimensions
[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 4
y = 2

[font]
size = 10

[font.offset]
y = 2

[font.glyph_offset]
y = 1
