#!/bin/sh

bspc config border_width 2
bspc config window_gap 0
bspc config focused_border_color \#ff8c00
bspc config split_ratio 0.5
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc monitor DisplayPort-0 -d web media dbx zoom vnc flt
bspc monitor DisplayPort-1 -d code dbx-code devbox a

bspc rule -a Slack desktop='dbx' follow=on
bspc rule -a Spotify desktop='media' follow=on
bspc rule -a discord desktop='media' follow=on
bspc rule -a zoom desktop='zoom' state=floating follow=on
bspc rule -a 1Password state=floating

# setup sxhkd
killall --quiet --wait --user $USER --exact sxhkd > /dev/null
sxhkd &

# set up polybar
killall --quiet --wait --user $USER --exact polybar > /dev/null
mkdir -p $HOME/.cache/logs
polybar main 2> $HOME/.cache/logs/polybar-main.err &
polybar term 2> $HOME/.cache/logs/polybar-term.err &

# make all windows on desktop 'flt' floating
killall --quiet --wait --user $USER --exact bspwm-floating > /dev/null
command -v bspwm-floating > /dev/null && bspwm-floating flt &

# set up nitrogen for background pictures
# no need to kill existing instances since when using `--restore` the process exits as soon as the background is set.
nitrogen --restore &

# tweak screen color to be easier on the eyes
redshift -P -O 4500

# Get the right hwmon path to monitor CPU temp in polybar.
# Specifically we are looking for the hardware monitor with name `k10temp` which is the driver that
# can read AMD CPU temps.
# Once we have matched on this `k10temp` name, we are looking for the right temperature among:
#  - Tdie -> the die temperature, that is the real measured temp
#  - Tctl -> the temperature control value, which is the reported temp
#  - Tccd{1..8} ->  the temperature of of the core complex dies.
# Tdie is most likely what we want since it's the most accurate and Tctl can be somewhat different
# since it is not necessarily the real measured temp and is instead used for fan control.
# See https://www.kernel.org/doc/html/v5.12/hwmon/k10temp.html
cpu_label="k10temp: Tctl"
for i in /sys/class/hwmon/hwmon*/temp*_input; do
    if [ "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*}))" = "$cpu_label" ]; then
        export HWMON_PATH="$i"
    fi
done
