#!/bin/sh

# kill the current running instances
pgrep -x sxhkd > /dev/null || sxhkd &

# kick off ssh-agent and set some options
eval $(ssh-agent)
xsetroot -cursor_name left_ptr

# set up nitrogen
nitrogen --restore &

# tweak screen color to be easier on eyes
redshift -P -O 4500

# set up polybar
killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar main &
polybar term &

bspc monitor DisplayPort-0 -d web media dbx
bspc monitor DisplayPort-1 -d code dbx-code

bspc config border_width 2
bspc config window_gap 2
bspc config focused_border_color \#ff8c00
bspc config split_ratio 0.52
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc rule -a firefoxdeveloperedition desktop='web' follow=on
bspc rule -a Google-chrome desktop='dbx' follow=on
bspc rule -a Slack desktop='dbx' follow=on
bspc rule -a zoom desktop='dbx' follow=on
bspc rule -a discord desktop='media' follow=on
