backend = "glx";
xrender-sync-fence = true;
vsync = true;

shadow = false;
fading = false;
corner-radius = 0;

blur-background = true;

blur:
{
  method = "dual_kawase";
  strength = 8;
};

# Uncomment the following to enable transparent blurry windows

# rules = (
#   { match = "class_g = 'Rofi'"; opacity = 0.8; },
#   { match = "class_g = 'Alacritty' && focused"; opacity = 0.9; },
#   { match = "class_g = 'Alacritty' && !focused"; opacity = 0.8; },
# );
