---

# This runs Yelp's `detect-secrets`: https://github.com/Yelp/detect-secrets/blob/master/README.md

name: Scan repo for secrets

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  check-for-secrets:
    name: 'Check for secrets'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Run Yelp's detect-secrets
        uses: nevermoe/detect-secrets-action@c9355b19ccab4679863738ad2d994096f8b0e79c # v1.7
