---
# This runs Yelp's `detect-secrets`: https://github.com/Yelp/detect-secrets/blob/master/README.md

name: Scan repo for secrets

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches:
      - "**"
    tags:
      - "!**"

jobs:
  check-for-secrets:
    name: "Check for secrets"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Yelp's detect-secrets
        uses: ddeville/detect-secrets-action@e64f53c71040a4457efeb1d264afabb1e596d0ce
