---

# This runs Yelp's `detect-secrets`: https://github.com/Yelp/detect-secrets/blob/master/README.md

name: Scan repo for secrets

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  check-for-secrets:
    name: 'Check for secrets'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Yelp's detect-secrets
        uses: nevermoe/detect-secrets-action@v1.7
