---

name: Run linters

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  stylua:
    # This runs `stylua`: https://github.com/JohnnyMorganz/StyLua
    name: Stylua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check config/common/.config/nvim
  sumneko:
    # This runs `sumneko`: https://github.com/mrcjkb/lua-typecheck-action
    name: Sumneko Lua
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run Sumneko Lua
      uses: mrcjkb/lua-typecheck-action@master
      with:
        directories: |
          config/common/.config/nvim
        configpath: .luarc.json
  shellcheck:
    # This runs `shellcheck`: https://www.shellcheck.net
    name: Shell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: style
  shfmt:
    # This runs `shfmt`: https://github.com/mvdan/sh and `checkbashisms`: https://linux.die.net/man/1/checkbashisms
    name: Shell Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run shfmt and checkbashisms
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHFMT_OPTS: --simplify --indent 2
        with:
          sh_checker_shellcheck_disable: true
          sh_checker_shfmt_disable: false
          sh_checker_checkbashisms_enable: true
  fish_indent:
    # This runs `fish_indent`: https://fishshell.com/docs/current/cmds/fish_indent.html
    name: Fish Indent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run fish_indent
        uses: ddeville/fish-indent-action@master
  vint:
    # This runs `vint`: https://github.com/Vimjas/vint
    name: Vint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: vint
        uses: ddeville/vint-action@master
