---

name: Run linters

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  stylua:
    # This runs `stylua`: https://github.com/JohnnyMorganz/StyLua
    name: Stylua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Stylua
        uses: JohnnyMorganz/stylua-action@v2
        with:
          version: latest
          args: --check config/common/.config/nvim
  shellcheck:
    # This runs `shellcheck`: https://www.shellcheck.net
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
